#cloud-config
version: v1
users:
  - name: local
  - name: ${vm_user_name}
    gecos: ${vm_user_displayname}
    passwd: ${vm_user_password}
    groups: sudo 
    lock_passwd: false
    shell: /bin/bash
    ssh_authorized_keys: ${vm_user_ssh_key}

apt:
  conf: |
    Acquire {
      Retries "60"
    }
    DPkg {
      Lock {
        Timeout "60"
      }
    }

package_update: true
packages_upgrade: true
packages:
  - net-tools
  - nmap
  - git
  - tree
  - openssh-server
  - sshpass
 # - ansible
 # - ansible-core

write_files:
  - content: |
      # first hosts_entry - always vcloud hostname/ip
      ${hosts_entry0}
      ${hosts_entry1} 
    path: /etc/hosts
    append: true
  - content: |
      #!/bin/bash
      export ip_net=$(echo ${master0_ip} |cut -d '.' -f1-3)
      for (( m=1;m<=${masters_count};m++ ));do ip=$((109+m)); echo "$ip_net.$ip  ${master_pref}-$m" >> /etc/hosts; done
      for (( w=1;w<=${workers_count};w++ ));do ip=$((113+w)); echo "$ip_net.$ip  ${worker_pref}-$w" >> /etc/hosts; done      
    path:  /add_hosts_records.sh
    permissions: "0744"

runcmd:
  - /add_hosts_records.sh
  - sed -i 's/PasswordAuthentication no/#PasswordAuthentication no/' /etc/ssh/sshd_config
  - [ systemctl, daemon-reload ]
  - [ systemctl, restart, --no-block, ssh.service ]